[package]
name = "panels"
version = "0.1.0"
description = "ETHBerlin 2022 Panel NFTs"
authors = ["nerfZael"]
repository = "https://github.com/nerfZael/koriander.git"
license = "MIT"
edition = "2021"

[dependencies]
polywrap-wasm-rs = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
